# Generated by Django 4.1.7 on 2023-03-06 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BrandModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("b_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_name", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("p_name", models.CharField(max_length=256)),
                ("p_desc", models.TextField()),
                ("p_img", models.FileField(upload_to="")),
                ("p_price", models.FloatField()),
                (
                    "p_brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apiApp.brandmodel",
                    ),
                ),
                (
                    "p_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apiApp.categorymodel",
                    ),
                ),
            ],
        ),
    ]
