# Generated by Django 4.1.7 on 2023-03-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandmodel",
            name="b_desc",
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name="categorymodel",
            name="c_desc",
            field=models.TextField(default=None),
        ),
    ]
