# Generated by Django 4.1.7 on 2023-03-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0003_alter_brandmodel_b_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorymodel",
            name="c_name",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="p_name",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
