# Generated by Django 4.1.7 on 2023-03-12 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("apiApp", "0005_usercart"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderDetailsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_count", models.IntegerField()),
                ("ft_name", models.CharField(max_length=200)),
                ("lt_name", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("town", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=200)),
                ("zip", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apiApp.productmodel",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
