# Generated by Django 4.1.7 on 2023-03-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0007_reviewmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="p_img",
            field=models.FileField(upload_to="media"),
        ),
    ]
