# Generated by Django 4.1.7 on 2023-03-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0008_alter_productmodel_p_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="p_img",
            field=models.ImageField(upload_to="media"),
        ),
    ]
