# Generated by Django 4.1.7 on 2023-03-14 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0009_alter_productmodel_p_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 14, 20, 8, 37, 39060)
            ),
        ),
    ]
