# Generated by Django 4.1.7 on 2023-03-14 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0010_productmodel_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 14, 20, 12, 1, 620077, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
