# Generated by Django 4.1.7 on 2023-03-14 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0012_alter_productmodel_date_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmodel",
            name="date_time",
        ),
        migrations.AddField(
            model_name="orderdetailsmodel",
            name="date_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
