# Generated by Django 4.1.7 on 2023-03-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0013_remove_productmodel_date_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetailsmodel",
            name="address",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="orderdetailsmodel",
            name="country",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="orderdetailsmodel",
            name="email",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="orderdetailsmodel",
            name="ft_name",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="orderdetailsmodel",
            name="lt_name",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="orderdetailsmodel",
            name="phone",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="orderdetailsmodel",
            name="state",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="orderdetailsmodel",
            name="town",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="orderdetailsmodel",
            name="zip",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
